lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_2/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_2_addon/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_3/urls.py
from django.conf.urls import url
from .views import index, add_activity

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_activity/$', add_activity, name='add_activity')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^$',RedirectView.as_view(permanent=True, url='/lab-2/')),
]

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

lab_2_addon/models.py
from django.db import models

# Create your models here.

lab_3/models.py
from django.db import models

# Create your models here.
class Diary(models.Model):
	date = models.DateTimeField()
	activity = models.TextField(max_length=60)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Rico Putra Pradana' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1998,1,21) #TODO Implement this, format (Year, Month, Date)
response = {}

# Create your views here.
def index(request):
	response['name'] = mhs_name
	response['age'] = calculate_age(birth_date.year)
	response['birth_date'] = 21
	response['birth_month'] = 'Januari'
	response['birth_year'] = 1998
	html = 'lab_1/index_lab1.html'
	return render(request, html, response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
# Create your views here.
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

landing_page_content = 'Welcome to MyBiodata'
response = {}
def index(request):
	response['name'] = mhs_name
	response['content'] = landing_page_content
	html = 'lab_2/lab_2.html'
	return render(request, html, response)

lab_2_addon/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

bio_dict = [{'subject':'Name', 'value':mhs_name},\
{'subject':'Birth Date', 'value': birth_date.strftime('%d %B %Y')},\
{'subject':'Sex', 'value': 'Male'}]
response = {}

# Create your views here.
def index(request):
	html = 'lab_2_addon/lab_2_addon.html'
	return render(request, html, response)

lab_3/views.py
from django.shortcuts import render, redirect
from .models import Diary
from datetime import datetime
import pytz


diary_dict = {}
response = {}
# Create your views here.
def index(request):
	html = 'lab_3/todolist.html'
	return render(request, html, {'diary_dict' : diary_dict})

def add_activity(request):
	if request.method == 'POST':
		date = datetime.strptime(request.POST['date'], '%Y-%m-%dT%H:%M')
		Diary.objects.create(date=date.replace(tzinfo=pytz.UTC),activity=request.POST['activity'])
		return redirect('/lab-3/')

lab_1/templates/lab_1/index_lab1.html
{% extends "lab_1/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<section class="welcome-page">
	<div class="container-fluid text-center">
		<h1 id="title-page">{{ name }}</h1>
		<h3>That's my name</h3>
		<article>I am {{ age }} years old</article>
	</div>
</section>
<!-- <section class="profile">
	<div class="row container-fluid">
		<div class="col-md-6 pic-space ">
			<img src="{% static 'img/Picture1.jpg' %}" id="pic">
		</div>
		<div class="col-md-6 profile-space">
			<div class="text-center">
				<h1 id="title-profile">MyProfile</h1>
			</div>
			
			<div class="sub-profile-space">
				<ul>
					<li>Nama	: {{ name }}</li>
					<li>TTL		: Bogor, {{ birth_date }} {{ birth_month }} {{ birth_year }}</li>
				</ul>

				<h1>Hello my name is {{ name }}</h1>
				<article>I am {{ age }} years old</article>
			</div>
			
		</div>
	</div>
	
</section> -->

{% endblock %}

lab_1/templates/lab_1/partials/footer.html
<div class="container-fluid footer">
	<div class="page-footer">
		<p>&copy; {{ name }}</p>
	</div>
</div>

lab_1/templates/lab_1/partials/header.html
<!-- fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'lab-1:index' %}">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'lab-1:index' %}">Age</a></li>
        <li><a href="{% url 'lab-2:index' %}">MyBiodata</a></li>
        <li><a href="{% url 'lab-2-addon:index' %}">MyBiodata2</a></li>
      </ul>
    </div>
  </div>
</nav>

lab_2/templates/lab_2/lab_2.html
{% extends 'lab_2/layout/base.html' %}
{% load staticfiles %}
{% load static %}

{% block content %}
<!-- HOME PAGE -->
<section class="jumbotron text-center">
	<h1>Company</h1> 
	<p>We specialize in blablabla</p> 

	<!-- Block code for the form -->
	<form class="form-inline">
		<div class="input-group">
			<input type="email" class="form-control" size="50" placeholder="Email Address required">
			<div class="input-group-btn">
				<button type="button" class="btn btn-danger">
					Subscribe
				</button>
			</div>
		</div>
	</form>
	<!-- Endblock for the FORM -->
</section>
<!-- END OF HOME PAGE -->

<!-- ABOUT COMPANY -->
<section class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<h2>About Company Page</h2>
			<h4>Lorem ipsum ..</h4>
			<p>Lorem ipsum ..</p>
			<button class="btn btn-default btn-lg">Get in Touch</button>
		</div>
		<div class="col-md-4">
			<span class="glyphicon glyphicon-signal logo"></span>
		</div>
	</div>
</section>
<!-- END OF ABOUT COMPANY -->

<!-- OUR VALUES -->
<section class="container-fluid bg-grey">
	<div class="row">
		<div class="col-md-4">
			<span class="glyphicon glyphicon-globe logo"></span>
		</div>
		<div class="col-md-8">
			<h2>Our Values</h2>
			<h4><strong>MISSION:</strong> Our mission lorem ipsum..</h4>
			<p><strong>VISSION:</strong> Our vision lorem ipsum</p>
		</div>
	</div>
</section>
<!-- END OF OUR VALUES -->

<!-- SERVICES -->
<section class="container-fluid text-center">
	<h2>SERVICES</h2>
	<h4>What we offer</h4>
	<br>
	<div class="row">
		<div class="col-sm-4">
			<span class="glyphicon glyphicon-off logo-small"></span>
			<h4>POWER</h4>
			<p>Lorem ipsum dolor sit amet..</p>
		</div>
		<div class="col-sm-4">
			<span class="glyphicon glyphicon-heart logo-small"></span>
			<h4>LOVE</h4>
			<p>Lorem ipsum dolor sit amet..</p>
		</div>
		<div class="col-sm-4">
			<span class="glyphicon glyphicon-lock logo-small"></span>
			<h4>JOB DONE</h4>
			<p>Lorem ipsum dolor sit amet..</p>
		</div>
	</div>
	<br><br>
	<div class="row">
		<div class="col-sm-4">
			<span class="glyphicon glyphicon-leaf logo-small"></span>
			<h4>GREEN</h4>
			<p>Lorem ipsum dolor sit amet..</p>
		</div>
		<div class="col-sm-4">
			<span class="glyphicon glyphicon-certificate logo-small"></span>
			<h4>CERTIFIED</h4>
			<p>Lorem ipsum dolor sit amet</p>
		</div>
		<div class="col-sm-4">
			<span class="glyphicon glyphicon-wrench logo-small"></span>
			<h4>HARD WORK</h4>
			<p>Lorem ipsum dolor sit amet..</p>
		</div>
	</div>
</section>
<!-- END OF SERVICES -->

<!-- PORTOFOLIO -->
<section class="container-fluid text-center bg-grey">
	<h2>PORTOFOLIO</h2>
	<br>
	<h4>What we have created</h4>
	<br>
	<div class="row text-center">
		<div class="col-sm-4">
			<div class="thumbnail">
				<img src="{% static 'img/book.jpeg' %}">
				<p><strong>BOOK ONE</strong></p>
				<p>Yes, this is the first</p>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="thumbnail">
				<img src="{% static 'img/book2.jpeg' %}">
				<p><strong>BOOK TWO</strong></p>
				<p>This is the second</p>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="thumbnail">
				<img src="{% static 'img/book3.jpeg' %}">
				<p><strong>BOOK THREE</strong></p>
				<p>This is the last</p>
			</div>
		</div>
	</div>
</section>
<!-- END of PORTOFOLIO -->

<!-- CAROUSEL -->
<section id="myCarousel" class="carousel slide text-center" data-ride="carousel">
	<!-- Indicator -->
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	</ol>

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<h4>"This company is the best. I am so happy with the result!"<br><span style="font-style: normal;">Michael Roe, Vice President, Comment Box</span></h4>
		</div>
		<div class="item">
			<h4>"One word... WOW!!"<br><span style="font-style: normal;">John Doe, Salesman, Rep Inc</span></h4>
		</div>
		<div class="item">
			<h4>"Could I... BE any more happy with this company?"<br><span style="font-style: normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
		</div>
	</div>

	<!-- Left and Right control -->
	<a href="#myCarousel" class="left carousel-control" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a href="#myCarousel" class="right carousel-control" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>

</section>
<!-- END of CAROUSEL -->
{% endblock %}

lab_2/templates/lab_2/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="LAB 2">
   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton:400,700">
   <link rel="stylesheet" type="text/css" href="{% static 'css/lab_2.css' %}">
   <title>{% block title %}Lab 2{% endblock %}</title>
</head>
<body>
   <header>
      
   </header>
   <content>
      {% block content %}

      {% endblock %}
   </content>
   <footer>
      <!-- {% include "lab_2/partials/footer.html" %} -->
   </footer>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

lab_2/templates/lab_2/partials/footer.html
<div class="container-fluid footer">
	<div class="page-footer">
		<p>&copy; {{ name }}</p>
	</div>
</div>

lab_2/templates/lab_2/partials/header.html
<!-- fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'lab-1:index' %}">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'lab-1:index' %}">Age</a></li>
        <li><a href="{% url 'lab-2:index' %}">MyBiodata</a></li>
        <li><a href="{% url 'lab-2-addon:index' %}">MyBiodata2</a></li>
      </ul>
    </div>
  </div>
</nav>

lab_2_addon/templates/lab_2_addon/lab_2_addon.html
{% extends 'lab_2_addon/layout/base.html' %}
{% block content %}
<section>
	
</section>
{% endblock %}

lab_2_addon/templates/lab_2_addon/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="LAB 2 Addon">
   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton:400,700">
   <title>Lab 2 Addon</title>
</head>
<body>
   <header>
      {% include "lab_2_addon/partials/header.html" %}
   </header>
   <content>
      {% block content %}

      {% endblock %}
   </content>
   <footer>
      {% include "lab_2_addon/partials/footer.html" %}
   </footer>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

lab_2_addon/templates/lab_2_addon/partials/footer.html
<div class="container-fluid footer">
	<div class="page-footer">
		<p>&copy; {{ name }}</p>
	</div>
</div>

lab_2_addon/templates/lab_2_addon/partials/header.html
<!-- fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'lab-1:index' %}">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'lab-1:index' %}">Age</a></li>
        <li><a href="{% url 'lab-2:index' %}">MyBiodata</a></li>
        <li><a href="{% url 'lab-2-addon:index' %}">MyBiodata2</a></li>
      </ul>
    </div>
  </div>
</nav>

lab_3/templates/lab_3/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="LAB 3">
   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton:400,700">
   <link rel="stylesheet" type="text/css" href="{% static 'css/lab_3.css' %}">
   <title>{% block title %}Lab 3{% endblock %}</title>
</head>
<body>
   <header>
   </header>
   <content>
      {% block content %}

      {% endblock %}
   </content>
   <footer>
   </footer>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

lab_3/templates/lab_3/todolist.html
{% extends 'lab_3/layout/base.html' %}
{% load staticfiles %}
{% load static %}

{% block content %}
<section>
	<div class="jumbotron text-center">
		<h1>Catatan Harianku</h1>
		<h4>Ceritakan harimu padaku.</h4>
	</div>
</section>
{% endblock %}